name = "advent-of-code"
version = "0.1.0"
defaultTargets = ["advent-of-code"]

[[lean_lib]]
name = "AdventOfCode"

[[lean_exe]]
name = "advent-of-code"
root = "Main"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries.git"
rev = "v4.20.0"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex.git"
rev = "v4.20.0"
subDir = "regex"
